[package]
name = "wyag"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5.35", features = ["derive"] }
configparser = "3.1.0"
flate2 = "1.1.1"
hex = "0.4.3"
log = "0.4.27"
ordered_hash_map = "0.4.0"
sha1 = "0.10.6"
